config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/index'
  get 'users/create'
  get 'users/show'
  get 'users/edit'
  get 'users/destroy'
  get 'sessions/new'
  resources :students
  resources :courses do
  resources :cohorts
end

  resources :instructors
  resources :cohorts
  resources :welcome

  delete 'terminate' => 'cohorts#destroy'
  resources :users
  # resources :sessions
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'


  root 'welcome#index'

  # get 'cohorts/new'
  # get 'cohorts/index'
  # get 'cohorts/edit'
  # get 'cohorts/show'
  # get 'instructors/index'
  # get 'instructors/edit'
  # get 'instructors/new'
  # get 'instructors/show'
  # get 'index/edit'
  # get 'index/new'
  # get 'index/show'
  # get 'courses/index'
  # get 'courses/show'
  # get 'courses/create'
  # get 'courses/new'
  # get 'courses/edit'
  # get 'courses/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_and_belongs_to_many :students
  belongs_to :course, optional: true
  belongs_to :instructor, optional: true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :cohorts

  def full_name
    self.first_name + " " + self.last_name
  end

end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :cohorts
  validates :first_name, length: { minimum: 2 }
   validates :last_name, length: { minimum: 2 }

   def full_name
     self.first_name + " " + self.last_name
   end


end

app/models/user.rb
class User < ApplicationRecord
  # before_save {self.email.downcase }
  # validates :name, presence: true, length: { maximum: 50 }
  # VALID_EMAIL_REGAX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true, length: {maximum: 255 },
  #             format: { with: VALID_EMAIL_REGAX},
  #             uniqueness: { case_sensitive: false }
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :null_session
  include SessionsHelper

end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def new
    @cohort = Cohort.new

  end

  def index
    @cohorts = Cohort.all
  end



  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.save
      redirect_to @cohort
    else
      render 'new'
    end
  end

  def show
    @cohort = Cohort.find(params[:id])
    @cohort.students << Student.find(params[:q][:student_ids]) if params[:q]
  end

  def destroy
    @cohort = Cohort.find(params[:id])
    @cohort.destroy
    respond_to do |format|
    format.js {render :layout => false}
    format.html {p 'html response';
    redirect_to root_path }
    end
  end


def update
  @cohort = Cohort.find(params[:id])
  @cohort.update(cohort_params)
  render 'show'
end

def edit
  @cohort = Cohort.find(params[:id])
  @cohort.students << Student.find(params[:q][:student_ids]) if params[:q]
end

private
def cohort_params
  params.require(:cohort) .permit(:cohort_name, :start_date, :end_date, :course_id, :student_id, :instructor_id)
end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course
    else
      render 'new'
    end
  end


  def new
    @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to @course
  else
    render 'edit'
  end
end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

  private
  def course_params
    params.require(:course) .permit(:coursename, :totalhours)
end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def index
    @instructors = Instructor.all
  end

  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      redirect_to @instructor
    else
      render 'new'
    end
  end

  def edit
    @instructor = Instructor.find(params[:id])
  end

  def new
    @instructor = Instructor.new
  end

  def show
    @instructor = Instructor.find(params[:id])
  end

  def update
    @instructor = Instructor.find(param[:id])
    if @instructor.update(student_params)
      redirect_to @instructor
    else
    render 'edit'
    end
  end

  def destroy
    @instructor = Instructor.find(params[:id])
    @instructor.destroy
    redirect_to instructors_path
  end

  private
  def instructor_params
    params.require(:instructor) .permit(:first_name, :last_name, :age, :salary, :education)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def index
  end

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'invalid email and password'
    render 'new'
  end
end

def destroy
  log_out
  redirect_to root_url
end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def create
    @student = Student.new(student_params)
    if @student.save
    redirect_to @student
    else
      render 'new'
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
      @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to @student
  else
    render 'edit'
  end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private
  def student_params
    params.require(:student).permit(:first_name, :last_name, :education)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])

  end

  def edit
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cohorts/_form.html.erb
<%= form_for @cohort do |f| %>

<% if @cohort.errors.any? %>
<div id="error_explanation">
   <h2><%= pluralize(@cohort.errors.count, "error") %> prohibited
     new instructor from being saved:</h2>
   <ul>
   <% @cohort.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
     <% end %>

   </ul>
 </div>
  <% end %>


<p>
<%= f.label :cohort_name %><br>
<%=f.text_field :cohort_name %>
</p>
<p>
<%= f.label :start_date %><br>
<%=f.date_field :start_date %>
</p>
<p>
<%= f.label :end_date %><br>
<%=f.date_field :end_date %>
</p>


<p>
<%= f.submit %>
</p>
<% end %>

app/views/cohorts/destroy.js.erb
$(‘.terminate’).bind(‘ajax:success’, function() {
console.log(‘deleting…’);
$(this).closest(‘p’).fadeOut();
});

app/views/cohorts/edit.html.erb
<%= render  'layouts/header' %>

<h1>Cohorts#edit</h1>
<h1>Edit cohort info</h1>
    <%= link_to 'Back', cohort_path %>

app/views/cohorts/index.html.erb
<%= render  'layouts/header' %>

<h1>Cohorts#index</h1>
<%= link_to 'add new cohort', new_cohort_path %>
<table>
<tr>
  <th>Cohort name</th>
  <th>Start date</th>
  <th>End date</th>
  <th>Instructor</th>
  <th>course name</th>

</tr>

<% @cohorts.each do |cohort| %>
<tr>
  <td><%= cohort.cohort_name %></td>
  <td><%= cohort.start_date %></td>
  <td><%= cohort.end_date %></td>
  <td><%= cohort.instructor.full_name if cohort.instructor %></td>
  <td><%= cohort.course.coursename if cohort.course %></td>


  <td><%= link_to cohort, method: :delete, data: { confirm: 'Are you certain? This action is irreversible' }, :remote => true, :class => 'delete_cohort' do %>
   DELETE
   <% end %></td>

  <td><%= link_to 'Show', cohort_path(cohort) %></td>
  <td><%= link_to 'Edit', edit_cohort_path(cohort) %></td>


</tr>
<% end %>
</table>

app/views/cohorts/new.html.erb
<%= render  'layouts/header' %>

<h1>cohort list</h1>
<%= render 'form' %>
<%= link_to 'Back', cohorts_path() %>

app/views/cohorts/show.html.erb
<%= render  'layouts/header' %>

<%= link_to 'Back', cohorts_path %>
<%= link_to 'terminate', cohort_path,
method: :delete, data: {confirm: 'are you sure', remote: true},
class: 'terminate' %>
<p>
  <strong>cohort name:</strong>
  <%= @cohort.cohort_name %>
</p>

<p>
  <strong>start date:</strong>
  <%= @cohort.start_date %>
</p>

<p>
  <strong>end date:</strong>
  <%= @cohort.end_date %>
</p>

<p>
  <strong>course name:</strong>
  <%= @cohort.course.coursename if @cohort.course %>
</p>

<p>
  <strong>instructor:</strong>
  <%= @cohort.instructor.full_name if @cohort.instructor%>
  <br>
</p>

<strong>student:</strong>
<% if @cohort.students %>
  <% @cohort.students.uniq.each do |z| %>
    <%= z.full_name %><br><% end %><br>
<% end %>
</p>

<h2>add instructor</h2>
<%= form_for @cohort do |f| %>
<%= f.collection_select(:instructor_id, Instructor.all, :id, :full_name) %>
<%= f.submit %>
<% end %>

<h2>add course</h2>
<%= form_for @cohort do |f| %>
<%= f.collection_select(:course_id, Course.all, :id, :coursename) %>
<%= f.submit %>
<% end %>


<p>


<h2>add student</h2>
<%= form_tag({controller: :cohorts, action: :update}, method: :get) %>
<%= collection_select(:q, :student_ids, Student.all, :id, :full_name) %>
<%= submit_tag ('submit') %>

app/views/instructors/_form.html.erb
<%= form_for @instructor do |f| %>

<% if @instructor.errors.any? %>
<div id="error_explanation">
   <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited
     new instructor from being saved:</h2>
   <ul>
   <% @instructor.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
     <% end %>

   </ul>
 </div>
  <% end %>


<p>
<%= f.label :first_name %><br>
<%=f.text_field :first_name %>
</p>
<p>
<%= f.label :last_name %><br>
<%=f.text_field :last_name %>
</p>
<p>
<%= f.label :age %><br>
<%=f.text_field :age %>
</p>

<p>
<%= f.label :education %><br>
<%=f.text_field :education %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/instructors/edit.html.erb
<h1>Instructor#edit</h1>
<h1>Edit instructor info</h1>
<%= render 'form' %>
    <%= link_to 'Back', instructor_path %>

app/views/instructors/index.html.erb
<h1>Instructor#index</h1>
<%= link_to 'add new instructor', new_instructor_path %>
<table>
<tr>
  <th>first name</th>
  <th>last name</th>
  <th>age</th>
  <th>education</th>

</tr>

<% @instructors.each do |instructor| %>
<tr>
  <td><%= instructor.first_name %></td>
  <td><%= instructor.last_name %></td>
  <td><%= instructor.age %></td>
  <td><%= instructor.education %></td>
  <td><%= instructor.salary %></td>
  <td><%= link_to 'Show', instructor_path(instructor) %></td>
  <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
  <td><%= link_to 'Delete', instructor_path(instructor), method: :delete,
  data: { confirm: 'are you sure?'} %></td>


</tr>
<% end %>
</table>

app/views/instructors/new.html.erb
<h1>course list</h1>
<%= render 'form' %>
<%= link_to 'Back', instructors_path() %>

app/views/instructors/show.html.erb
<%= link_to 'Back', instructor_path %>

<p>
  <strong>first name:</strong>
  <%= @instructor.first_name %>
</p>

<p>
  <strong>last name:</strong>
  <%= @instructor.last_name %>
</p>
<p>
  <strong>age:</strong>
  <%= @instructor.age %>
</p>
<p>
  <strong>salary:</strong>
  <%= @instructor.salary %>
</p>
<p>
  <strong>education:</strong>
  <%= @instructor.education %>
</p>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>

<% if @student.errors.any? %>
<div id="error_explanation">
   <h2><%= pluralize(@student.errors.count, "error") %> prohibited
     new student from being saved:</h2>
   <ul>
   <% @student.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
     <% end %>

   </ul>
 </div>
  <% end %>


<p>
<%= f.label :first_name %><br>
<%=f.text_field :first_name %>
</p>
<p>
<%= f.label :last_name %><br>
<%=f.text_field :last_name %>
</p>
<p>
<%= f.label :education %><br>
<%=f.text_field :education %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/students/edit.html.erb
<%= render  'layouts/header' %>

<h1>Edit student info</h1>
<%= render 'form' %>
    <%= link_to 'Back', student_path %>

app/views/students/index.html.erb
<%= render  'layouts/header' %>

<h1>students' list</h1>
<%= link_to 'add student', new_student_path %>
<table>
<tr>
  <th>First name</th>
  <th>Last name</th>
  <th>Education</th>
</tr>

<% @students.each do |student| %>
<tr>
  <td><%= student.first_name %></td>
  <td><%= student.last_name %></td>
  <td><%= student.education %></td>
  <td><%= link_to 'Show', student_path(student) %></td>
  <td><%= link_to 'Edit', edit_student_path(student) %></td>
  <td><%= link_to 'Delete', student_path(student), method: :delete,
  data: { confirm: 'are you sure?'} %></td>
</tr>
<p>howdyddd</p>
<% end %>
</table>

app/views/students/new.html.erb
<%= render  'layouts/header' %>

<h1>student list</h1>
<%= render 'form' %>
<%= link_to 'Back', students_path() %>

app/views/students/show.html.erb
<%= render  'layouts/header' %>

<%= link_to 'Back', students_path %>

<p>
  <strong>first name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>education:</strong>
  <%= @student.education %>
</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= render  'layouts/header' %>

<h1>Users#new</h1>
<% if @user.errors.any? %>
<div id="error_explanation">
   <h2><%= pluralize(@course.errors.count, "error") %> prohibited
     new account from being saved:</h2>
     <ul>
       <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
       </ul>
     </div>
   <% end %>

<p>Find me in app/views/users/new.html.erb</p>
  <%= form_for @user do |form| %>
  <%= form.label :name  %>
  <%= form.text_field :name %> <br>
    <%= form.label :email  %>
    <%= form.text_field :email %> <br>
    <%= form.label :password %>
    <%= form.password_field :password %> <br>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %> <br>
    <%= form.submit "sign up"%>

<% end %>

app/views/users/show.html.erb
<h1>Users#show  thank you for sign up</h1>
<p><%= @user.email %></p>

<%= link_to 'Logout', logout_path %>
<%= link_to 'home', root_path %>
<%= render  'layouts/header' %>