config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/index'
  get 'users/create'
  get 'users/show'
  get 'users/edit'
  get 'users/destroy'
  get 'sessions/new'
  resources :students
  resources :courses do
  resources :cohorts
end

  resources :instructors
  resources :cohorts
  resources :welcome

  delete 'terminate' => 'cohorts#destroy'
  resources :users
  # resources :sessions
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'


  root 'welcome#index'

  # get 'cohorts/new'
  # get 'cohorts/index'
  # get 'cohorts/edit'
  # get 'cohorts/show'
  # get 'instructors/index'
  # get 'instructors/edit'
  # get 'instructors/new'
  # get 'instructors/show'
  # get 'index/edit'
  # get 'index/new'
  # get 'index/show'
  # get 'courses/index'
  # get 'courses/show'
  # get 'courses/create'
  # get 'courses/new'
  # get 'courses/edit'
  # get 'courses/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  has_and_belongs_to_many :students
  belongs_to :course, optional: true
  belongs_to :instructor, optional: true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :cohorts
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :cohorts

  def full_name
    self.first_name + " " + self.last_name
  end

end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :cohorts
  validates :first_name, length: { minimum: 2 }
   validates :last_name, length: { minimum: 2 }

   def full_name
     self.first_name + " " + self.last_name
   end


end

app/models/user.rb
class User < ApplicationRecord
  # before_save {self.email.downcase }
  # validates :name, presence: true, length: { maximum: 50 }
  # VALID_EMAIL_REGAX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  # validates :email, presence: true, length: {maximum: 255 },
  #             format: { with: VALID_EMAIL_REGAX},
  #             uniqueness: { case_sensitive: false }
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :null_session
  include SessionsHelper

end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  def new
    @cohort = Cohort.new

  end

  def index
    @cohorts = Cohort.all
  end



  def create
    @cohort = Cohort.new(cohort_params)
    if @cohort.save
      redirect_to @cohort
    else
      render 'new'
    end
  end

  def show
    @cohort = Cohort.find(params[:id])
    @cohort.students << Student.find(params[:q][:student_ids]) if params[:q]
  end

  def destroy
    @cohort = Cohort.find(params[:id])
    @cohort.destroy
    respond_to do |format|
    format.js {render :layout => false}
    format.html {p 'html response';
    redirect_to root_path }
    end
  end


def update
  @cohort = Cohort.find(params[:id])
  @cohort.update(cohort_params)
  render 'show'
end

def edit
  @cohort = Cohort.find(params[:id])
  @cohort.students << Student.find(params[:q][:student_ids]) if params[:q]
end

private
def cohort_params
  params.require(:cohort) .permit(:cohort_name, :start_date, :end_date, :course_id, :student_id, :instructor_id)
end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      redirect_to @course
    else
      render 'new'
    end
  end


  def new
    @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to @course
  else
    render 'edit'
  end
end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
  end

  private
  def course_params
    params.require(:course) .permit(:coursename, :totalhours)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def index
  end

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'invalid email and password'
    render 'new'
  end
end

def destroy
  log_out
  redirect_to root_url
end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def create
    @student = Student.new(student_params)
    if @student.save
    redirect_to @student
    else
      render 'new'
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def edit
      @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to @student
  else
    render 'edit'
  end
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to students_path
  end

  private
  def student_params
    params.require(:student).permit(:first_name, :last_name, :education)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])

  end

  def edit
  end

  def destroy
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>

<% if @course.errors.any? %>
<div id="error_explanation">
   <h2><%= pluralize(@course.errors.count, "error") %> prohibited
     new course from being saved:</h2>
   <ul>
   <% @course.errors.full_messages.each do |msg| %>
     <li><%= msg %></li>
     <% end %>

   </ul>
 </div>
  <% end %>


<p>
<%= f.label :coursename %><br>
<%= f.text_field :coursename %>
</p>
<p>
<%= f.label :totalhours %><br>
<%=f.text_field :totalhours %>
<!-- f.collection_select :student, Student.all, :id, :name    -->
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/courses/edit.html.erb
<h1>Courses#edit</h1>
<h1>Edit course info</h1>
<%= render 'form' %>
    <%= link_to 'Back', course_path %>

app/views/courses/index.html.erb
<h1>Courses#index</h1>
<%= link_to 'add new course', new_course_path %>
<table>
<tr>
  <th>Course name</th>
  <th>Total hours</th>
</tr>

<% @courses.each do |course| %>
<tr>
  <td><%= course.coursename %></td>
  <td><%= course.totalhours %></td>
  <td><%= link_to 'Show', course_path(course) %></td>
  <td><%= link_to 'Edit', edit_course_path(course) %></td>
  <td><%= link_to 'Delete', course_path(course), method: :delete,
  data: { confirm: 'are you sure?'} %></td>


</tr>
<% end %>
</table>

app/views/courses/new.html.erb
<h1>course list</h1>
<%= render 'form' %>
<%= link_to 'Back', courses_path() %>

app/views/courses/show.html.erb
<%= link_to 'Back', courses_path %>

<p>
  <strong>course name:</strong>
  <%= @course.coursename %>
</p>

<p>
  <strong>total hours:</strong>
  <%= @course.totalhours %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome dashboard</h1>
<p>please login to use dashboard</p>
<%= link_to 'login', login_path %>
<p>please sign up first if you are a new member</p>
<%= link_to 'signup', new_user_path %>

app/views/welcome/show.html.erb
<%= render  'layouts/header' %>